$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  rules:
    type: object
    properties:
      fileconversion:
        type: boolean
      preprocessing:
        type: boolean
      GNPSexport:
        type: boolean
      requantification:
        type: boolean
      sirius:
        type: boolean
      annotate:
        type: boolean

required:
  - samples
  - rules